name: Build AridityTeam.Base

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    - name: Restore dependencies
      run: dotnet restore src/libraries/AridityTeam.Base/AridityTeam.Base.sln
    - name: Build
      run: dotnet build --no-restore src/libraries/AridityTeam.Base/AridityTeam.Base.sln
    - name: Test
      run: dotnet test --no-build --verbosity normal src/libraries/AridityTeam.Base/tests/AridityTeam.Base.Tests.csproj
