name: Build AridityTeam.Base (Linux)

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
env:
  MAIN_BASE_SLN: "src/libraries/AridityTeam.Base/AridityTeam.Base.sln"
  MAIN_BASE_TEST_PROJ: "src/libraries/AridityTeam.Base/tests/AridityTeam.Base.Tests.csproj"
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    - name: Restore dependencies
      run: dotnet restore ${MAIN_BASE_SLN}
      working-directory: ${{ github.workspace }}
    - name: Build
      run: dotnet build --no-restore ${MAIN_BASE_SLN}
      working-directory: ${{ github.workspace }}
    - name: Test
      run: dotnet test --no-build --verbosity normal ${MAIN_BASE_TEST_PROJ}
      working-directory: ${{ github.workspace }}
