name: Pack AridityTeam.Base

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
env:
  MAIN_BASE_SLN: "src/libraries/AridityTeam.Base/AridityTeam.Base.sln"
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x
          source-url: https://nuget.pkg.github.com/AridityTeam/index.json
        env:
          NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}     
      - name: Restore dependencies in all projects
        run: dotnet restore ${MAIN_BASE_SLN}
        working-directory: ${{ github.workspace }}
      - name: Build and Generate NuGet packages
        run: dotnet pack --no-restore -c Release -o ./out ${MAIN_BASE_SLN}
        working-directory: ${{ github.workspace }}
      - name: Push packages into GitHub
        run: dotnet nuget push ./out/*.nupkg --skip-duplicate --no-symbols true
        working-directory: ${{ github.workspace }}